[package]
name = "retro"
version = "0.2.0"
authors = ["Gabriel Dos Santos <dss.gabriel@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
